FROM jenkins:latest

MAINTAINER feiyyang <fei-yang.yang@keysight.com>


#USER root

COPY executors.groovy /usr/share/jenkins/ref/init.groovy.d/executors.groovy


# Install Jenkins Plugins
RUN /usr/local/bin/install-plugins.sh \
      workflow-aggregator \
      docker-workflow \
      slack \
      copyartifact \
      jobConfigHistory \
      build-timeout \
      disk-usage \
      email-ext \
      sonar \
      ec2 \
      build-monitor-plugin \
      matrix-auth \
      blueocean \
      swarm \
      msbuild \
      embeddable-build-status \
      artifactory 
      
      


# Skip initial setup
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false




RUN git config --global user.email "fei-yang.yang@keysight.com" && \
    git config --global user.name "feiyyang"



